version: '3.8'
services:
  db:
    image: postgres
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    
    
    restart: always
    
  app: 
    build: ./
    env_file:
      - .env-non-dev
    container_name: test_courier
    ports:
      - 7773:8000
    depends_on:
      - db
    restart: always